inputPath: "/Users/misery/GolandProjects/bingo/mmap"
outputPath: "/Users/misery/GolandProjects/bingo/mmap1"
faultPoints:
  - faultType: "ConditionInversedFault"
    locationPattern:
      - packageP:
          - name: "util"
            activationRate: "2/3"
        structP: "*"
        methodP:
          - name: "main"
            activationRate: "1/2"
        variableP:
          - name: "*"
              activationRate: "1/2"
    targetValue: "hello world"
